spring.application.name=eatplatform

#profiles
spring.profiles.active=${active}

#MySQL
spring.datasource.url=jdbc:mysql://${mysqlHost}/eatplatform?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${mysqlUser}
spring.datasource.password=${mysqlPassword}

#MyBatis
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.eatplatform.vo

#Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8