spring.application.name=eatplatform

#profiles
spring.profiles.active=${active}

#MyBatis
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.eatplatform.vo

#Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8